########## df0 #############
df0_columns = [
    "timestamp",
    "email_add",
    "name",
    "phone_number",
    "dob",
    "gender",
    "maths_marks_pc",
    "science_marks_pc",
    "sst_marks_pc",
    "english_marks_pc",
    "hindi_marks_pc",
    "computer_marks_pc",
    "avg_study_time_home",
    "schedule_follow_flg",
    "father_prof",
    "mother_prof",
    "grand_father_prof",
    "grand_mother_prof",
    "grand_mother_prof",
    "grade",
    "school_name",
]

######### df1 ################################

mapping_dict1 = {
    "timestamp": "Timestamp",
    "email_add": "Email Address",
    "name": "Name",
    "email": "Email",
    "phone_number": "Phone number",
    "dob": "Date Of Birth",
    "gender": "Gender",
    "t1_q1": "1. You regularly make new friends.",
    "t1_q2": "2. You spend a lot of your free time exploring various random topics that pique your interest",
    "t1_q3": "3. Seeing other people cry can easily make you feel like you want to cry too",
    "t1_q4": "4. You often make a backup plan for a backup plan.",
    "t1_q5": "5. You usually stay calm, even under a lot of pressure",
    "t1_q6": "6. At social events, you rarely try to introduce yourself to new people and mostly talk to the ones you already know",
    "t1_q7": "7. You prefer to completely finish one project before starting another.",
    "t1_q8": "8. You are very sentimental.",
    "t1_q9": "9. You like to use organizing tools like schedules and lists.",
    "t1_q10": "10. Even a small mistake can cause you to doubt your overall abilities and knowledge.",
    "t1_q11": "11. You feel comfortable just walking up to someone you find interesting and striking up a conversation.",
    "t1_q12": "12. You are not too interested in discussing various interpretations and analyses of creative works.",
    "t1_q13": "13. You are more inclined to follow your head than your heart.",
    "t1_q14": "14. You usually prefer just doing what you feel like at any given moment instead of planning a particular daily routine.",
    "t1_q15": "15. You rarely worry about whether you make a good impression on people you meet.",
    "t1_q16": "16. You enjoy participating in group activities.",
    "t1_q17": "17. You like books and movies that make you come up with your own interpretation of the ending.",
    "t1_q18": "18. Your happiness comes more from helping others accomplish things than your own accomplishments.",
    "t1_q19": "19. You are interested in so many things that you find it difficult to choose what to try next.",
    "t1_q20": "20. You are prone to worrying that things will take a turn for the worse.",
    "t1_q21": "21. You avoid leadership roles in group settings.",
    "t1_q22": "22. You are definitely not an artistic type of person.",
    "t1_q23": "23. You think the world would be a better place if people relied more on rationality and less on their feelings.",
    "t1_q24": "24. You prefer to do your chores before allowing yourself to relax.",
    "t1_q25": "25. You enjoy watching people argue.",
    "t1_q26": "26. You tend to avoid drawing attention to yourself.",
    "t1_q27": "27. Your mood can change very quickly.",
    "t1_q28": "28. You lose patience with people who are not as efficient as you.",
    "t1_q29": "29. You often end up doing things at the last possible moment.",
    "t1_q30": "30. You have always been fascinated by the question of what, if anything, happens after death.",
    "t1_q31": "31. You usually prefer to be around others rather than on your own.",
    "t1_q32": "32. You become bored or lose interest when the discussion gets highly theoretical.",
    "t1_q33": "33. You find it easy to empathize with a person whose experiences are very different from yours.",
    "t1_q34": "34. You usually postpone finalizing decisions for as long as possible.",
    "t1_q35": "35. You rarely second-guess the choices that you have made.",
    "t1_q36": "36. After a long and exhausting week, a lively social event is just what you need.",
    "t1_q37": "37. You enjoy going to art museums.",
    "t1_q38": "38. You often have a hard time understanding other people’s feelings.",
    "t1_q39": "39. You like to have a to-do list for each day.",
    "t1_q40": "40. You rarely feel insecure.",
    "t1_q41": "41. You avoid making phone calls.",
    "t1_q42": "42. You often spend a lot of time trying to understand views that are very different from your own.",
    "t1_q43": "43. In your social circle, you are often the one who contacts your friends and initiates activities.",
    "t1_q44": "44. If your plans are interrupted, your top priority is to get back on track as soon as possible.",
    "t1_q45": "45. You are still bothered by mistakes that you made a long time ago.",
    "t1_q46": "46. You rarely contemplate the reasons for human existence or the meaning of life.",
    "t1_q47": "47. Your emotions control you more than you control them.",
    "t1_q48": "48. You take great care not to make people look bad, even when it is completely their fault.",
    "t1_q49": "49. Your personal work style is closer to spontaneous bursts of energy than organized and consistent efforts.",
    "t1_q50": "50. When someone thinks highly of you, you wonder how long it will take them to feel disappointed in you.",
    "t1_q51": "51. You would love a job that requires you to work alone most of the time.",
    "t1_q52": "52. You believe that pondering abstract philosophical questions is a waste of time.",
    "t1_q53": "53. You feel more drawn to places with busy, bustling atmospheres than quiet, intimate places.",
    "t1_q54": "54. You know at first glance how someone is feeling.",
    "t1_q55": "55. You often feel overwhelmed.",
    "t1_q56": "56. You complete things methodically without skipping over any steps.",
    "t1_q57": "57. You are very intrigued by things labeled as controversial.",
    "t1_q58": "58. You would pass along a good opportunity if you thought someone else needed it more.",
    "t1_q59": "59. You struggle with deadlines.",
    "t1_q60": "60. You feel confident that things will work out for you.",
    "t1_q61": "1. Career",
    "t1_q62": "2. Passion",
    "t1_q63": "3. Parents",
    "t1_q64": "4. Teacher",
    "t1_q65": "5. Inspiration",
    "t1_q66": "6. Ambition/ Life's goal/ life's AIM",
}

df1_columns = [
    "timestamp",
    "email_add",
    "name",
    "email",
    "phone_number",
    "dob",
    "gender",
    "t1_q1",
    "t1_q2",
    "t1_q3",
    "t1_q4",
    "t1_q5",
    "t1_q6",
    "t1_q7",
    "t1_q8",
    "t1_q9",
    "t1_q10",
    "t1_q11",
    "t1_q12",
    "t1_q13",
    "t1_q14",
    "t1_q15",
    "t1_q16",
    "t1_q17",
    "t1_q18",
    "t1_q19",
    "t1_q20",
    "t1_q21",
    "t1_q22",
    "t1_q23",
    "t1_q24",
    "t1_q25",
    "t1_q26",
    "t1_q27",
    "t1_q28",
    "t1_q29",
    "t1_q30",
    "t1_q31",
    "t1_q32",
    "t1_q33",
    "t1_q34",
    "t1_q35",
    "t1_q36",
    "t1_q37",
    "t1_q38",
    "t1_q39",
    "t1_q40",
    "t1_q41",
    "t1_q42",
    "t1_q43",
    "t1_q44",
    "t1_q45",
    "t1_q46",
    "t1_q47",
    "t1_q48",
    "t1_q49",
    "t1_q50",
    "t1_q51",
    "t1_q52",
    "t1_q53",
    "t1_q54",
    "t1_q55",
    "t1_q56",
    "t1_q57",
    "t1_q58",
    "t1_q59",
    "t1_q60",
    "t1_q61",
    "t1_q62",
    "t1_q63",
    "t1_q64",
    "t1_q65",
    "t1_q66",
]

df1_model_params_list = [
    "t1_q1",
    "t1_q2",
    "t1_q3",
    "t1_q4",
    "t1_q5",
    "t1_q6",
    "t1_q7",
    "t1_q8",
    "t1_q9",
    "t1_q10",
    "t1_q11",
    "t1_q12",
    "t1_q13",
    "t1_q14",
    "t1_q15",
    "t1_q16",
    "t1_q17",
    "t1_q18",
    "t1_q19",
    "t1_q20",
    "t1_q21",
    "t1_q22",
    "t1_q23",
    "t1_q24",
    "t1_q25",
    "t1_q26",
    "t1_q27",
    "t1_q28",
    "t1_q29",
    "t1_q30",
    "t1_q31",
    "t1_q32",
    "t1_q33",
    "t1_q34",
    "t1_q35",
    "t1_q36",
    "t1_q37",
    "t1_q38",
    "t1_q39",
    "t1_q40",
    "t1_q41",
    "t1_q42",
    "t1_q43",
    "t1_q44",
    "t1_q45",
    "t1_q46",
    "t1_q47",
    "t1_q48",
    "t1_q49",
    "t1_q50",
    "t1_q51",
    "t1_q52",
    "t1_q53",
    "t1_q54",
    "t1_q55",
    "t1_q56",
    "t1_q57",
    "t1_q58",
    "t1_q59",
    "t1_q60",
]

######### df2 ##########################################

df2_columns1 = ["timestamp", "email_add", "name", "phone_number", "dob", "gender"]
df2_columns2 = ["t2_q{}".format(i + 1) for i in range(144)]
df2_columns = df2_columns1 + df2_columns2

######### df3 ##########################################

mapping_dict3 = {
    "timestamp": "Timestamp",
    "email_add": "Email Address",
    "name": "Name",
    "phone_number": "Phone number",
    "dob": "Date Of Birth",
    "gender": "Gender",
    "t3_q1": "1. Which of the following is a prime number?",
    "t3_q2": "2. If ( x + 2 = 7 ), then the value of ( 3x ) is:",
    "t3_q3": "3. If the perimeter of a rectangle is 36 cm and its length is 10 cm, what is its breadth?",
    "t3_q4": "4. If the area of a circle is ( 49pi) sq. cm, what is its radius?",
    "t3_q5": "5. The value of ( 15/100 times 500 ) is:",
    "t3_q6": "6. What is the LCM of 12 and 18?",
    "t3_q7": "7. What is the perimeter of a square whose area is 81 sq. cm?",
    "t3_q8": "8. If ( a = 2 ) and ( b = 3 ), then the value of ( a^2 + b^2 - 2ab ) is:",
    "t3_q9": "9. What is the cube root of 512?",
    "t3_t10": "10. The simple interest on Rs. 8000 for 2 years at an annual interest rate of 5% is:",
    "t3_q11": "11. The average of the numbers ( 10, 20, 30, 40, 50 ) is:",
    "t3_q12": "12. The ratio of 5 liters to 500 milliliters is:",
    "t3_q13": "13. What is the value of (100/0.25)?",
    "t3_q14": "14. If ( x^2 = 64), what is the value of ( x )?",
    "t3_q15": "15. Which of the following is a Pythagorean triplet?",
    "t3_q16": "1. What is the SI unit of force?",
    "t3_q17": "2. Which of the following is a scalar quantity?",
    "t3_q18": "3. If an object is moving with constant velocity, what is the net force acting on it?",
    "t3_q19": "4. What is the relation between mass (m), acceleration (a), and force (F)?",
    "t3_q20": "5. In which medium does sound travel the fastest?",
    "t3_q21": "6. Which of the following phenomena explains why we see lightning before hearing thunder?",
    "t3_q22": "7. Which of the following energy transformations occurs in a hydroelectric power plant?",
    "t3_q23": "8. A freely falling object experiences...",
    "t3_q24": "9. What is the kinetic energy of an object with a mass of 2 kg moving at 3 m/s?",
    "t3_q25": "10. What is the frequency of a wave if its time period is 0.01 seconds?",
    "t3_q26": "1. Which of the following is NOT a chemical change?",
    "t3_q27": "2. The chemical symbol for Sodium is...",
    "t3_q28": "3. The number of protons in the nucleus of an atom is called its...",
    "t3_q29": "4. Which of the following is a heterogeneous mixture?",
    "t3_q30": "5. Which of the following elements is a noble gas?",
    "t3_q31": "6. The pH of a neutral solution at 25°C is...",
    "t3_q32": "7. Which of the following methods can be used to separate salt from seawater?",
    "t3_q33": "8. In the periodic table, elements in the same group have the same...",
    "t3_q34": "9. Which of the following metals reacts vigorously with water?",
    "t3_q35": "10. Which of the following is an alloy?",
    "t3_q36": "1. Which of the following is the basic structural and functional unit of life?",
    "t3_q37": "2. Which cell organelle is known as the 'powerhouse' of the cell?",
    # "t3_q37": "2. Which cell organelle is known as the ‘powerhouse’ of the cell?",
    "t3_q38": "3. What is the main function of the xylem in plants?",
    "t3_q39": "4. In which part of the plant does photosynthesis take place?",
    "t3_q40": "5. The green pigment in plants responsible for photosynthesis is:",
    "t3_q41": "6. Which of the following organisms are prokaryotic?",
    "t3_q42": "7. Which part of the human body is primarily responsible for absorbing nutrients from food?",
    "t3_q43": "8. The process of cell division in which a single cell divides into two identical daughter cells is called:",
    "t3_q44": "9. Which of the following is NOT a characteristic of living organisms?",
    "t3_q45": "10. Which of the following is a genetic material?",
    "t3_q46": "11. Which disease is caused by a deficiency of Vitamin C?",
    "t3_q47": "12. Which of the following organelles is responsible for protein synthesis?",
    "t3_q48": "13. Which type of blood vessel carries blood away from the heart?",
    "t3_q49": "14. What is the function of the enzyme amylase?",
    "t3_q50": "15. Which part of the brain controls balance and coordination?",
    "t3_q51": "1. What was the main aim of the French Revolution?",
    "t3_q52": "2. Which of the following is not a characteristic of democracy?",
    "t3_q53": "3. The Earth’s lithosphere consists of which of the following?",
    "t3_q54": "4. Which of the following countries is not a member of the SAARC?",
    "t3_q55": "5. Which of the following is a Rabi crop?",
    "t3_q56": '6. Which river is known as the "Sorrow of Bengal"?',
    "t3_q57": "7. Who is known as the ‘Father of Indian Constitution’?",
    "t3_q58": "8. Which revolution is related to the increase in milk production in India?",
    "t3_q59": "9. What is the significance of the Tropic of Cancer for India?",
    "t3_q60": "10. Which of the following is a natural cause of soil erosion?",
    "t3_q61": "11. The fundamental right to equality ensures which of the following?",
    "t3_q62": "12. What was the main feature of the Indian economy before British rule?",
    "t3_q63": "13. In which year was the Quit India Movement launched?",
    "t3_q64": "14. Which of the following is a biotic component of the environment?",
    "t3_q65": "15. Who was the first President of India?",
    "t3_q66": "16. Which country’s constitution influenced the Indian Constitution the most in terms of fundamental rights?",
    "t3_q67": "17. The type of farming in which crops are grown to meet the needs of the farmer’s family is known as:",
    "t3_q68": "18. What is the primary source of energy for the Earth’s climate system?",
    "t3_q69": "19. Which of the following is the oldest mountain range in India?",
    "t3_q70": "20. Which movement was started by Mahatma Gandhi in 1919 against the Rowlatt Act?",
}

df3_columns = [
    "timestamp",
    "email_add",
    "name",
    "phone_number",
    "dob",
    "gender",
    "t3_q1",
    "t3_q2",
    "t3_q3",
    "t3_q4",
    "t3_q5",
    "t3_q6",
    "t3_q7",
    "t3_q8",
    "t3_q9",
    "t3_t30",
    "t3_q11",
    "t3_q12",
    "t3_q13",
    "t3_q14",
    "t3_q15",
    "t3_q16",
    "t3_q17",
    "t3_q18",
    "t3_q19",
    "t3_q20",
    "t3_q21",
    "t3_q22",
    "t3_q23",
    "t3_q24",
    "t3_q25",
    "t3_q26",
    "t3_q27",
    "t3_q28",
    "t3_q29",
    "t3_q30",
    "t3_q31",
    "t3_q32",
    "t3_q33",
    "t3_q34",
    "t3_q35",
    "t3_q36",
    "t3_q37",
    "t3_q38",
    "t3_q39",
    "t3_q40",
    "t3_q41",
    "t3_q42",
    "t3_q43",
    "t3_q44",
    "t3_q45",
    "t3_q46",
    "t3_q47",
    "t3_q48",
    "t3_q49",
    "t3_q50",
    "t3_q51",
    "t3_q52",
    "t3_q53",
    "t3_q54",
    "t3_q55",
    "t3_q56",
    "t3_q57",
    "t3_q58",
    "t3_q59",
    "t3_q60",
    "t3_q61",
    "t3_q62",
    "t3_q63",
    "t3_q64",
    "t3_q65",
    "t3_q66",
    "t3_q67",
    "t3_q68",
    "t3_q69",
    "t3_q70",
]


################ df4 #############################

mapping_dict4 = {
    "timestamp": "Timestamp",
    "email_add": "Email Address",
    "name": "Name",
    "phone_number": "Phone number",
    "dob": "Date Of Birth",
    "gender": "Gender",
    "t4_q1": "1. Select the word which is opposite in meaning to the given word 'Optimistic'",
    "t4_q2": "2. Find the missing term in the series. A, D, G, J, ?  ",
    "t4_q3": "3. Identify the relationship between the given pair and choose the pair with the same relationship. Pen: Write :: Knife : ?",
    "t4_q4": "4. Choose the correct synonym for the word  'OBSTINATE'",
    "t4_q5": "5. Complete the analogy. Lion: Roar :: Snake : ?",
    "t4_q6": "6. Choose the option that best completes the sentence. \n'If I were rich, I __________ travel the world.'",
    "t4_q7": "7. Find the odd one out. Horse, Cow, Dog, Whale_",
    "t4_q8": "8. Identify the grammatically correct sentence.",
    "t4_q9": "9. Which of the following words is misspelled?",
    "t4_t10": "10. Rearrange the following words to form a meaningful sentence. given / a / was / the / prize / winner / the / to ",
    "t4_q11": "1. Find the missing number in the sequence. 2, 6, 12, 20, ?",
    "t4_q12": "2. Complete the analogy. Book : Read :: Knife : ?",
    "t4_q13": "3. Identify the odd one out. Apple, Orange, Banana, Carrot",
    "t4_q14": "4. If the code for CAT is DBU, what is the code for DOG?",
    "t4_q15": "5. Which word does not belong to the group? Rectangle, Triangle, Circle, Pentagon",
    "t4_q16": "6. Select the option that continues the pattern. AB, CD, EF, GH, ?",
    "t4_q17": "7. In a certain code language, if PAPER is coded as OBOFS, what is the code for PENCIL?",
    "t4_q18": "8. Which of the following numbers is divisible by 3? 25, 33, 19, 22 ",
    "t4_q19": "9. If all BLOOD is RED and all RED is COLOR, what can we infer? ",
    "t4_q20": "10. Rearrange the letters to form a meaningful word. GOLRITHM",
    "t4_q21": "1. You notice a classmate is being bullied during lunch. What would you do?",
    "t4_q22": "2. During a group project, one of your teammates is not contributing. What is the best way to handle the situation?",
    "t4_q23": "3. You see someone accidentally drop money on the floor and walk away. What should you do?",
    "t4_q24": "4. You are preparing for an important exam but your friends invite you to a party the night before. What is the best option?",
    "t4_q25": "5. You are working on a project and your friend copies your work without your permission. What would you do?",
    "t4_q26": "6. Your teacher asks you to complete an assignment by the next day, but you also have a family event. How would you handle it?",
    "t4_q27": "7. You find out that a classmate has failed the exam. How would you support them?",
    "t4_q28": "8. You notice a group of friends excluding someone from your class activities. What should you do?  ",
    "t4_q29": "9. During a school trip, you notice that your friend is not following the rules. How would you handle it?",
    "t4_q30": "10. You were chosen to lead a group project, but one of your teammates disagrees with your ideas. What should you do?",
    "t4_q31": "1. Listen to their ideas and try to reach a compromise.",
    "t4_q32": "2. I work towards a solution in conflicts that respects everyone’s needs.",
    "t4_q33": "3. I can easily sense others' feelings and imagine what they might be going through.",
    "t4_q34": "4. I express understanding and provide emotional support when someone shares their problems with me.",
    "t4_q35": "5. I often take initiatives that benefit other people or the community.",
    "t4_q36": "6. I willingly share my resources with others who might need them, even if I receive nothing in return.",
    "t4_q37": "7. I can maintain my composure and think clearly even when under significant emotional stress.",
    "t4_q38": "8. I use strategies (like deep breathing, taking a break, etc.) to manage my emotions effectively.",
    "t4_q39": "9. I am aware of my emotions as they arise and understand how they affect my behavior.",
    "t4_q40": "10. I can pinpoint the specific factors that trigger different emotional responses in me.",
    "t4_q41": "11. I feel confident in my ability to handle my emotional responses in various situations.",
    "t4_q42": "12. I believe in my capacity to manage difficult emotional situations and regain my stability.",
    "t4_q43": "13. I am self-motivated to pursue my goals, regardless of minor setbacks.",
    "t4_q44": "14. I consistently seek out new challenges and opportunities for growth and learning.",
    "t4_q45": "What is your school Name",
    "t4_q46": "Your school's annual fee",
}

df4_columns = [
    "timestamp",
    "email_add",
    "name",
    "phone_number",
    "dob",
    "gender",
    "t4_q1",
    "t4_q2",
    "t4_q3",
    "t4_q4",
    "t4_q5",
    "t4_q6",
    "t4_q7",
    "t4_q8",
    "t4_q9",
    "t4_t10",
    "t4_q11",
    "t4_q12",
    "t4_q13",
    "t4_q14",
    "t4_q15",
    "t4_q16",
    "t4_q17",
    "t4_q18",
    "t4_q19",
    "t4_q20",
    "t4_q21",
    "t4_q22",
    "t4_q23",
    "t4_q24",
    "t4_q25",
    "t4_q26",
    "t4_q27",
    "t4_q28",
    "t4_q29",
    "t4_q30",
    "t4_q31",
    "t4_q32",
]
